name: 'Simple MS Teams Webhook notifier'
description: 'simple typescript template for building GitHub Actions'
author: 'LuisGhz'
inputs:
  webhook_url:
    description: Webhook url
    required: true
  summary:
    description: Summary field
    required: false
    default: ''
  title:
    description: Title field
    required: false
    default: ''
  text:
    description: Text field
    required: false
    default: ''
  theme-color:
    description: Theme color field
    required: false
    default: 28a745
  sections:
    description: Sections field
    required: false
    default: ''
  potential-action:
    description: Actions field
    required: false
    default: ''
  yaml-ident:
    description: The number of spaces to use when indenting code
    required: false
    default: '2'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: "blue"
  icon: "bell"  
